# Generated by Django 4.0.4 on 2023-01-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('Units', models.SmallIntegerField()),
                ('IC_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
