# Generated by Django 4.0.4 on 2023-01-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='IC_Name',
        ),
    ]
