# Generated by Django 4.0.4 on 2023-01-05 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huels', '0002_remove_courses_ic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2023)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('overall_exp', models.DecimalField(decimal_places=1, max_digits=2)),
                ('liteness', models.DecimalField(decimal_places=1, max_digits=2)),
                ('grade_sat', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pr', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='IC_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr', models.IntegerField()),
                ('experience', models.TextField(max_length=1000)),
                ('liteness', models.DecimalField(decimal_places=1, max_digits=2)),
                ('grade_sat', models.DecimalField(decimal_places=1, max_digits=2)),
                ('positives', models.TextField(max_length=500)),
                ('negatives', models.TextField(max_length=500)),
                ('tips', models.TextField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huels.courses')),
                ('sem', models.ManyToManyField(to='huels.sementry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
