# Generated by Django 4.0.2 on 2023-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0004_sementry_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sem',
            field=models.ManyToManyField(to='huels.SemEntry'),
        ),
    ]
