# Generated by Django 4.0.2 on 2023-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0005_alter_review_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='IC_Name',
        ),
        migrations.RemoveField(
            model_name='sementry',
            name='prof',
        ),
        migrations.AddField(
            model_name='sementry',
            name='IC_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
