# Generated by Django 4.0.2 on 2023-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0006_remove_courses_ic_name_remove_sementry_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sementry',
            name='IC_Name',
        ),
        migrations.AddField(
            model_name='courses',
            name='IC_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sementry',
            name='prof',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
