# Generated by Django 4.1.5 on 2023-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0008_rename_course_review_reviewed_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sementry',
            old_name='prof',
            new_name='IC_Name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='IC_Name',
        ),
        migrations.AlterField(
            model_name='review',
            name='grade_sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='liteness',
            field=models.IntegerField(default=0),
        ),
    ]
