# Generated by Django 4.1.1 on 2023-01-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0009_rename_prof_sementry_ic_name_remove_courses_ic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='review',
            name='negatives',
        ),
        migrations.RemoveField(
            model_name='review',
            name='positives',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_course',
        ),
        migrations.AddField(
            model_name='review',
            name='overall_exp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='grade_sat',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='liteness',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.RemoveField(
            model_name='review',
            name='sem',
        ),
        migrations.AddField(
            model_name='review',
            name='sem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='huels.sementry'),
            preserve_default=False,
        ),
    ]
