# Generated by Django 4.1.1 on 2023-01-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huels', '0010_remove_review_experience_remove_review_negatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='huels.sementry'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
