# Generated by Django 4.2.3 on 2023-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huels', '0011_alter_review_sem_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.TextField(default='No About for this HuEl'),
        ),
    ]
